/* empty css                      */import{a as q,S as v,i as s}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();let h=1;const E=15,P="https://pixabay.com/api/",R="47437973-d70be85f5be71cfd9f8f29695";async function g(e){try{const t=await q(P,{params:{key:R,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:h,per_page:E}});return console.log(t.data),t.data}catch(t){throw console.error("Error fetching pictures:",t.message),new Error("Failed to fetch pictures")}}async function H(){h+=1}async function M(){h=1}function y(e){return e.map(({webformatURL:t,largeImageURL:i,tags:l,likes:r,views:o,comments:c,downloads:S})=>`
    <a class="gallery-item" href="${i}">
      <div class="all-gallery">
        <img src="${t}" alt="${l}">
        <div class="description">
          <p>Likes: <span>${r}</span></p>
          <p>Views: <span>${o}</span></p>
          <p>Comments: <span>${c}</span></p>
          <p>Downloads: <span>${S}</span></p>
        </div>
      </div>
    </a>
  `).join("")}function $(e){e.innerHTML=""}function m(e){e.style.display="block"}function L(e){e.style.display="none"}function d(e){e.style.display="block"}function f(e){e.style.display="none"}const w=document.querySelector(".form-search"),u=document.querySelector(".gallery"),p=document.querySelector(".loader"),n=document.querySelector(".js-load-more");let b=new v(".gallery-item",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250});w.addEventListener("submit",O);n.addEventListener("click",B);let a=0;async function O(e){e.preventDefault();const t=e.target.elements.query.value.trim();if(!t){s.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}$(u),m(p),M(),a=0;try{const i=await g(t);if(!i.hits.length){s.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u.innerHTML=y(i.hits),b.refresh(),a+=i.hits.length,a>=i.totalHits?(f(n),s.info({message:"You've reached the end of search results.",position:"topRight"})):d(n)}catch{s.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"}),f(n)}finally{L(p)}}async function B(){m(p),f(n);try{await H();const e=w.elements.query.value.trim();if(!e){s.error({title:"Error",message:"Search query is empty!",position:"topRight"});return}const t=await g(e);a+=t.hits.length,a>=t.totalHits?s.info({message:"You've reached the end of search results.",position:"topRight"}):d(n),u.insertAdjacentHTML("beforeend",y(t.hits)),b.refresh();const i=u.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:i*1.2,behavior:"smooth"})}catch{s.error({title:"Error",message:"Error fetching more images!",position:"topRight"})}finally{L(p),a<data.totalHits&&d(n)}}
//# sourceMappingURL=index.js.map
